export type BackgroundImageMap = {
  [key: string]: {
    [key: string]: string;
  };
};
/* eslint-disable @typescript-eslint/no-require-imports */
export const backgroundImages: BackgroundImageMap = {
  timi: {
    introduction_timi: require('@/app/assets/images/timi/introduction_timi.gif'),
    reveil_timi: require('@/app/assets/images/timi/reveil_timi.gif'),
    short_timi: require('@/app/assets/images/timi/short_timi.gif'),
    pantalon_timi: require('@/app/assets/images/timi/pantalon_timi.gif'),
    petit_dej_timi: require('@/app/assets/images/timi/petit_dej_timi.gif'),
    asteroides_timi: require('@/app/assets/images/timi/asteroides_timi.gif'),
    baies_de_lune_timi: require('@/app/assets/images/timi/baies_de_lune_timi.gif'),
    trajet_aller_timi: require('@/app/assets/images/timi/trajet_aller_timi.gif'),
    hoverboard_timi_aller: require('@/app/assets/images/timi/hoverboard_timi_aller.gif'),
    baskets_timi_aller: require('@/app/assets/images/timi/baskets_timi_aller.gif'),
    arrivee_ecole_timi: require('@/app/assets/images/timi/arrivee_ecole_timi.gif'),
    discussion_passage_asteroide_timi: require('@/app/assets/images/timi/discussion_passage_asteroide_timi.gif'),
    ballon_flottant_timi: require('@/app/assets/images/timi/ballon_flottant_timi.gif'),
    ecole_matin_timi: require('@/app/assets/images/timi/ecole_matin_timi.gif'),
    musique_timi: require('@/app/assets/images/timi/musique_timi.gif'),
    arts_plastiques_timi: require('@/app/assets/images/timi/arts_plastiques_timi.gif'),
    recreation_matin_timi: require('@/app/assets/images/timi/recreation_matin_timi.gif'),
    billes_timi: require('@/app/assets/images/timi/billes_timi.gif'),
    discussion_vacances_timi: require('@/app/assets/images/timi/discussion_vacances_timi.gif'),
    sport_timi: require('@/app/assets/images/timi/sport_timi.gif'),
    course_timi: require('@/app/assets/images/timi/course_timi.gif'),
    ping_pong_timi: require('@/app/assets/images/timi/ping_pong_timi.gif'),
    dejeuner_timi: require('@/app/assets/images/timi/dejeuner_timi.gif'),
    poisson_timi: require('@/app/assets/images/timi/poisson_timi.gif'),
    omelette_timi: require('@/app/assets/images/timi/omelette_timi.gif'),
    ecole_aprem_timi: require('@/app/assets/images/timi/ecole_aprem_timi.gif'),
    geographie_timi: require('@/app/assets/images/timi/geographie_timi.gif'),
    histoire_timi: require('@/app/assets/images/timi/histoire_timi.gif'),
    recreation_aprem_timi: require('@/app/assets/images/timi/recreation_aprem_timi.gif'),
    cache_cache_timi: require('@/app/assets/images/timi/cache_cache_timi.gif'),
    chat_perche_timi: require('@/app/assets/images/timi/chat_perche_timi.gif'),
    ecole_fin_timi: require('@/app/assets/images/timi/ecole_fin_timi.gif'),
    calcul_timi: require('@/app/assets/images/timi/calcul_timi.gif'),
    ecriture_timi: require('@/app/assets/images/timi/ecriture_timi.gif'),
    retour_timi: require('@/app/assets/images/timi/retour_timi.gif'),
    hoverboard_timi_retour: require('@/app/assets/images/timi/hoverboard_timi_retour.gif'),
    baskets_timi_retour: require('@/app/assets/images/timi/baskets_timi_retour.gif'),
    soiree_timi: require('@/app/assets/images/timi/soiree_timi.gif'),
    jeu_video_timi: require('@/app/assets/images/timi/jeu_video_timi.gif'),
    lecture_timi: require('@/app/assets/images/timi/lecture_timi.gif'),
    fin_timi: require('@/app/assets/images/timi/fin_timi.gif'),
  },
  alex: {},
};
